// src/character/component/CharacterDisplayNameView.tsx
import { useTranslation } from 'react-i18next';
import { Character } from '../model/Character';

export const CharacterDisplayNameView = ({ character }: { character: Character }) => {
  const { t } = useTranslation();
  return <span className="font-bold">{character.displayName.getReactElement({ t })}</span>;
};

// src/frontend/component/character-display-name-view.svelte
<script lang="ts">
  import type { Character } from '../../engine/core/character/model/character';
  import TranslatableTextView from '../../i18n/translatable-text-view.svelte';

  export let character: Character;
</script>

<span class="font-bold"><TranslatableTextView text={character.displayName} /></span>
