// src/map/component/FieldView.tsx
import { MapField } from '../model/MapField';
export const FieldView = ({ field }: { field: MapField }) => {
  if (field.object) {
    return (
      <div className="relative -z-[100]">
        <img className="absolute" src={field.fieldType.imageUrl} width={64} height={64}></img>
        <img className="absolute" src={field.object.imageUrl} width={64} height={64}></img>
      </div>
    );
  } else if (field.fieldType.imageUrl) {
    return <img src={field.fieldType.imageUrl} width={64} height={64}></img>;
  } else {
    return <div className="w-[64px] h-[64px] bg-white"></div>;
  }
};

// src/frontend/component/field-view.svelte
<script lang="ts">
  import type { MapField } from '../../engine/core/map/model/map-field';

  export let field: MapField;
</script>

{#if field.terrainObjects.length > 0}
  <div class="relative -z-[100]">
    <img class="absolute" src={field.fieldType.imageUrl} alt="Terrain" width={64} height={64} />
    <img class="absolute" src={field.terrainObjects.get(0).imageUrl} alt="Terrain object" width={64} height={64} />
  </div>
{:else}
  <img src={field.fieldType.imageUrl} alt="Terrain" width={64} height={64} />
{/if}
