// src/frontend/component/character-profile-view.svelte
<script lang="ts">
  import type { Character } from '../../engine/core/character/model/character';
  import CharacterAvatarView from './character-avatar-view.svelte';
  import CharacterDisplayNameView from './character-display-name-view.svelte';

  export let character: Character;
</script>

<div class="flex divide-x-[2px] divide-black">
  <CharacterAvatarView {character} />
  <div class="pl-[8px] pt-[3px]">
    <CharacterDisplayNameView {character} />
  </div>
</div>

// src/character/component/CharacterProfileView.tsx
import { Character } from '../model/Character';
import { CharacterDisplayNameView } from './CharacterDisplayNameView';
import { CharacterAvatarView } from './CharacterAvatarView';

export const CharacterProfileView = ({ character }: { character: Character }) => {
  return (
    <div className="flex divide-x-[2px] divide-black">
      <CharacterAvatarView character={character} />
      <div className="pl-[8px] pt-[3px]">
        <CharacterDisplayNameView character={character} />
      </div>
    </div>
  );
};
