// src/action/component/ActionPanel.tsx
import ReactModal from 'react-modal';
import { ActionContext } from '../model/ActionContext';
import { ActionExecutionContext } from '../model/ActionExecutionContext';
import { useTranslation } from 'react-i18next';

export const ActionPanel = ({
  actionContext,
  actionExecutionContext
}: {
  actionContext: ActionContext;
  actionExecutionContext: ActionExecutionContext;
}) => {
  const { t } = useTranslation();

  return (
    <ReactModal
      isOpen={true}
      ariaHideApp={false}
      className="absolute left-[50%] top-[50%] translate-x-[-50%] translate-y-[-50%] w-[800px] min-h-[600px] max-h-[80%] bg-white border-[2px] border-black divide-y-[2px] divide-black"
      overlayClassName="fixed inset-0"
    >
      <div className="p-[10px]">
        <span>{actionContext.title.getReactElement({ t })}</span>
        {!actionContext.isActionRequired && (
          <button onClick={actionExecutionContext.doNotTakeAction} className="float-right">
            X
          </button>
        )}
      </div>
      <div className="p-[10px] overflow-auto">
        {actionContext.description.character && actionContext.description.character.avatarUrl && (
          <img
            src={actionContext.description.character.avatarUrl}
            width={64}
            height={64}
            className="float-left border-[2px] border-black mr-[10px]"
          ></img>
        )}
        {actionContext.description.text.getReactElement({ t })}
      </div>
      <div className="p-[10px]">
        {actionContext.actions.map((action) => (
          <div
            key={action.id}
            onClick={() => action.executeAction(actionExecutionContext)}
            className="cursor-pointer text-blue-700 hover:text-blue-400"
          >
            {t(action.getNameTranslationKey())}
          </div>
        ))}
      </div>
    </ReactModal>
  );
};

// src/action/component/action-panel.svelte
<!-- App.svelte -->
<script lang="ts">
  import TranslatableTextView from '../../i18n/translatable-text-view.svelte';
  import type { ActionContext } from '../model/action-context';
  import type { ActionExecutionContext } from '../model/action-execution-context';

  export let actionContext: ActionContext;
  export let actionExecutionContext: ActionExecutionContext;
</script>

<div
  class="fixed bg-white top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%] border-[2px] border-black divide-y-[2px] divide-black w-[800px] h-[600px]"
>
  <div class="p-[10px]">
    <TranslatableTextView text={actionContext.title} />
    {#if !actionContext.isActionRequired}
      <button on:click={actionExecutionContext.doNotTakeAction} class="float-right">X</button>
    {/if}
  </div>
  <div class="p-[10px] overflow-auto">
    {#if actionContext.description.character && actionContext.description.character.avatarUrl}
      <img
        src={actionContext.description.character.avatarUrl}
        alt="Character avatar"
        width={64}
        height={64}
        class="float-left border-[2px] border-black mr-[10px]"
      />
    {/if}
    <TranslatableTextView text={actionContext.description.text} />
  </div>
  <div class="p-[10px]">
    {#each actionContext.actions as action}
      <div on:click={() => action.executeAction(actionExecutionContext)} class="cursor-pointer text-blue-700 hover:text-blue-400">
        <TranslatableTextView text={action.name} />
      </div>
    {/each}
  </div>
</div>
