// src/map/component/field-view.svelte
<script lang="ts">
  import type { MapField } from '../model/map-field';

  export let field: MapField;
</script>

{#if field.terrainObject}
  <div class="relative -z-[100]">
    <img class="absolute" src={field.fieldType.imageUrl} alt="Terrain" width={64} height={64} />
    <img class="absolute" src={field.terrainObject.imageUrl} alt="Terrain object" width={64} height={64} />
  </div>
{:else if field.fieldType.imageUrl}
  <img src={field.fieldType.imageUrl} alt="Terrain" width={64} height={64} />
{:else}
  <div class="w-[64px] h-[64px] bg-white" />
{/if}

// src/map/component/FieldView.tsx
import { MapField } from '../model/MapField';
export const FieldView = ({ field }: { field: MapField }) => {
  if (field.terrainObject) {
    return (
      <div className="relative -z-[100]">
        <img className="absolute" src={field.fieldType.imageUrl} width={64} height={64}></img>
        <img className="absolute" src={field.terrainObject.imageUrl} width={64} height={64}></img>
      </div>
    );
  } else if (field.fieldType.imageUrl) {
    return <img src={field.fieldType.imageUrl} width={64} height={64}></img>;
  } else {
    return <div className="w-[64px] h-[64px] bg-white"></div>;
  }
};
