// src/App.tsx
import i18next from 'i18next';
import React, { useEffect, useState } from 'react';
import { ActionPanel } from './action/component/ActionPanel';
import { ActionContext } from './action/model/ActionContext';
import { ActionExecutionContext } from './action/model/ActionExecutionContext';
import { MapFieldActionTrigger } from './action/model/MapFieldActionTrigger';
import { getActionContextByActionTrigger } from './action/service/ActionService';
import './App.css';
import { CharacterProfileView } from './character/component/CharacterProfileView';
import { CharacterPosition } from './character/model/CharacterPosition';
import * as MockedGame from './game/mock/MockedGame';
import { LocationView } from './map/component/LocationVIiew';
import { MapField } from './map/model/MapField';

function App() {
  const [gameState, setGameState] = useState(MockedGame.gameState);
  useEffect(() => {
    i18next.addResourceBundle('en', 'translation', {
      'CHARACTER.RACE.HUMAN': 'Human',
      'MAP.TERRAIN_OBJECT.HOUSE': 'House',
      'MAP.TERRAIN_OBJECT.HOUSE.DESCRIPTION': 'The house seems normal.'
    });
    i18next.addResourceBundle('pl', 'translation', {
      'CHARACTER.RACE.HUMAN': 'Człowiek',
      'MAP.TERRAIN_OBJECT.HOUSE': 'Dom',
      'MAP.TERRAIN_OBJECT.HOUSE.DESCRIPTION': 'Do wygląda normalnie.'
    });
  }, []);

  const [actionContext, setActionContext] = useState<ActionContext | undefined>(undefined);
  const actionExecutionContext = new ActionExecutionContext(
    () => setActionContext(undefined),
    (actionContext) => setActionContext(actionContext),
    (field) => {
      gameState.player.character.position = new CharacterPosition({ field: field });
      setActionContext(undefined);
    }
  );

  const displayActionPanelForField = (field: MapField) => {
    const actionTrigger = new MapFieldActionTrigger(field);
    const actionContext = getActionContextByActionTrigger(actionTrigger, gameState);
    setActionContext(actionContext);
  };

  return (
    <div className="border-2 border-black divide-y-[2px] divide-black h-full flex flex-col">
      <CharacterProfileView character={gameState.player.character}></CharacterProfileView>
      <div className="grow overflow-hidden">
        <LocationView
          gameState={gameState}
          onGameStateChange={setGameState}
          onFieldClick={({ field }) => displayActionPanelForField(field)}
        />
      </div>
      {actionContext && <ActionPanel actionContext={actionContext} actionExecutionContext={actionExecutionContext}></ActionPanel>}
    </div>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import ActionPanel from './action/component/action-panel.svelte';
  import type { ActionContext } from './action/model/action-context';
  import { ActionExecutionContext } from './action/model/action-execution-context';
  import { MapFieldActionTrigger } from './action/model/map-field-action-trigger';
  import { getActionContextByActionTrigger } from './action/service/action-service';
  import CharacterProfileView from './character/component/character-profile-view.svelte';
  import { CharacterPosition } from './character/model/character-position';
  import * as MockedGame from './game/mock/mocked-game';
  import type { GameState } from './game/model/game-state';
  import { initLocalizationContext } from './i18n/translation-service';
  import LocationView from './map/component/location-view.svelte';
  import type { MapField } from './map/model/map-field';

  const { i18n } = initLocalizationContext();
  i18n.addResourceBundle('en', 'common', {
    'MAP.TERRAIN_OBJECT.HOUSE': 'House',
    'MAP.TERRAIN_OBJECT.HOUSE.DESCRIPTION': 'The house seems normal.'
  });
  i18n.addResourceBundle('pl', 'common', {
    'MAP.TERRAIN_OBJECT.HOUSE': 'Dom',
    'MAP.TERRAIN_OBJECT.HOUSE.DESCRIPTION': 'Dom wygląda normalnie.'
  });

  let actionContext: ActionContext | undefined = undefined;
  let gameState: GameState = MockedGame.gameState;

  const actionExecutionContext = new ActionExecutionContext(
    () => (actionContext = undefined),
    (newActionContext) => (actionContext = newActionContext),
    (field) => {
      gameState.player.character.position = new CharacterPosition({
        field: field
      });
      actionContext = undefined;
    }
  );

  function displayActionPanelForField(field: MapField) {
    const actionTrigger = new MapFieldActionTrigger(field);
    actionContext = getActionContextByActionTrigger(actionTrigger, gameState);
  }
</script>

<div class="border-2 border-black divide-y-[2px] divide-black h-full flex flex-col">
  <CharacterProfileView character={gameState.player.character} />
  <div class="grow overflow-hidden">
    <LocationView {gameState} onGameStateChange={(newGameState) => (gameState = newGameState)} onFieldClick={displayActionPanelForField} />
  </div>
</div>

{#if actionContext}
  <ActionPanel {actionContext} {actionExecutionContext} />
{/if}

<style lang="postcss" global>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>
